### ISSUE TITLE
try-runtime-bot is sometimes not responding

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/try-runtime-bot#35]
e.g. https://github.com/paritytech/polkadot/pull/4772#issuecomment-1028595106

**Comment by joao-paulo-parity** [comment]
I think it happened on https://github.com/paritytech/polkadot/pull/4772#issuecomment-1028595106 because the bot is not installed in Polkadot. The problem is I don't know who to ask for checking those installations because @TriplEight is OOO.

@kirushik could you please check if the try-runtime-bot Github App is installed on https://github.com/paritytech/polkadot? You _might_ (I can't verify it) be able to find the app in https://github.com/organizations/paritytech/settings/installations with an admin account.

**Comment by wabkebab** [comment]
Hi!

 try-runtime-bot Github App  is only installed in paritytech/substrate

**Comment by joao-paulo-parity** [comment]
@wabkebab thanks for checking. It should be installed in https://github.com/paritytech/polkadot as well as per https://github.com/paritytech/polkadot/pull/4772.

**Comment by wabkebab** [comment]
Can you try now?

**Comment by joao-paulo-parity** [comment]
> Can you try now?

It worked! Closing this issue
